config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  
  resources :portfolios do
    put :sort, on: :collection
    member do 
      get :toggle_status
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
  
  get 'support', to: 'support#new', as: 'new_support'
  post 'support', to: 'support#create', as: 'create_support'

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

end

app/models/message.rb
class Message

  include ActiveModel::Model
  attr_accessor :name, :company, :email, :project_description, :budget
  validates :name, :email, :project_description, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to new_message_path, notice: "Message received"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :company, :email, :project_description, :budget)
  end
end

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
<%= notice %>
<%= @message.errors.full_messages.join(', ') %>
<div class="row justify-content-md-center">
  <div class="about-us col-md-9">
    <h1>We are very excited to work with you!</h1>
    <p>We Offer Full Stack Services in Web Application as well as Mobile Application Development</p>
    <p>See our <%= link_to "Portfolio", portfolios_path %> for more details and samples of our work</p>
    <div class="row justify-content-md-center">
      <div class="col-md-4">
        <p><%= f.text_field :name, placeholder: 'Name', class: "form-control" %></p>
        <p><%= f.text_field :company, placeholder: 'Company', class: "form-control" %></p>
        <p><%= f.email_field :email, placeholder: 'Email', class: "form-control" %></p>
      </div>
      <div class="col-md-8">
        <p><%= f.text_area :project_description, placeholder: 'Project Description', size: '120x6', class: "form-control" %></p>
      </div>
    </div>
    <%= f.submit 'Send', class: "btn btn-outline-dark" %>
    <% end %>
  </div>
</div>