config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  
  resources :portfolios do
    put :sort, on: :collection
    member do 
      get :toggle_status
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
  
  get 'support', to: 'support#new', as: 'new_support'
  post 'support', to: 'support#create', as: 'create_support'

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1}
    validates_presence_of :title, :body

    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, admin: :all

  def index
    if logged_in?(:admin)
      @blogs = Blog.page(params[:page]).per(10)
    else
      @blogs = Blog.published.page(params[:page]).per(10)
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
      if @blog.save
        redirect_to blog_path(@blog)
      else
        render :new
      end
  end

  def edit
  end
  
  def update
      if @blog.update(blog_params)
        @blog.save
        redirect_to @blog, notice: 'Your blog was edited successfully'
      else
        render :edit
      end
  end

  def show
    @blog = Blog.friendly.find(params[:id])
  end
  
  def destroy
    if @blog.destroy
          redirect_to blogs_path, notice: 'Your blog was destroyed successfully'
      else
        render :show, notice: 'Your blog could not be destroyed'
      end
  end



  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end      
    redirect_to blog_path, notice:  "#{@blog.title} status has been updated."
  end


  private

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
          params.require(:blog).permit(:title, :body)
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post about-us">
  <h2 class="blog-link"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <p>
    <%= markdown blog.body.truncate(250) %> <span class=""><%= link_to "Continue Reading", blog %></span>
  </p>
</div>

app/views/blogs/_form.html.erb
<div class="row justify-content-md-center">
  <div class="about-us">

    <%= form_for @blog do |f| %>
    <% notice %>
    <div class="row justify-content-md-center">
      <div class="col-md-4">
        <%= f.text_field :title, placeholder: "Title", class: 'form-control' %><br />
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-11">
        <%= f.text_area :body, row: 10, size: "80x10", placeholder: "Blog Body", class: 'form-control'%><br />
      </div>

    </div>
    <%= f.submit "Submit", class: 'btn btn-outline-dark' %>
  </div>
  <%#= f.fields_for :gamplats do |gamplats_form| %>
  <%#= render 'gamplat_fields', f: gamplats_form %>
  <%# end %>

  <div>
    <%#= link_to_add_association 'Add New Platform', f, :gamplats %>
  </div>
  
  <%#= f.fields_for :game_gallaries do |gallary_form|  %>
  <%#= render 'game_gallary_fields', f: gallary_form %>
  <%# end %>

  <div>
    <%#= link_to_add_association 'Add New Gallery Item', f, :game_gallaries %>
  </div>

  
  <% end %>
</div>
</div>

app/views/blogs/index.html.erb
<div class="page-title">
<h1>Another day at Paraiso!</h1>
</div>
<% if logged_in?(:admin) %>
  <%= link_to "New Blog", new_blog_path, class: "btn btn-outline-dark" %>
<% end%>

<div class="row justify-content-md-center paginate-bar">
<%= paginate @blogs %>
</div>

<div>
<%= render @blogs %>
</div>

<div class="row justify-content-md-center paginate-bar">
<%= paginate @blogs %>
</div>
	

app/views/blogs/show.html.erb
<h2 class="page-title"> <%= @blog.title.titleize %></h2>

<div class="row justify-content-md-center">
<% if logged_in?(:admin) %>

<div class="about-us col-md-3 margin-20">
	<h4>ADMIN OPTIONS</h4>
	<%= link_to "Edit", edit_blog_path(@blog), class: "about-us pageinate" %>
	<%= link_to "Delete", @blog, method: :delete, data:  {confirm: "Are you sure you want to delete?"},class: "about-us pageinate" %>
	<%= link_to "#{@blog.status}", toggle_status_blog_path(@blog), class: "about-us pageinate #{@blog.status}" %>
</div>
<% end %>

</div>
<div class="row justify-content-md-center">


<div class="col-md-9 about-us margin-20">
<div class="alight-right"><%= markdown @blog.body %></div>
</div>
</div>
</div>