config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  
  resources :portfolios do
    put :sort, on: :collection
    member do 
      get :toggle_status
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
  
  get 'support', to: 'support#new', as: 'new_support'
  post 'support', to: 'support#create', as: 'create_support'

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  enum status: { draft: 0, published: 1}
  validates_presence_of :title, :description

  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: :all_blank, allow_destroy: true

  has_many :gallery_items
  accepts_nested_attributes_for :gallery_items, reject_if: :all_blank, allow_destroy: true

  mount_uploader :thumbnail_image, ImageUploader
	mount_uploader :main_image, ImageUploader

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show, :index], user: {except: [:destroy, :new ,:create, :update, :edit, :sort]}, admin: :all

  def index
    if logged_in?(:admin)
      @portfolios = Portfolio.all
    else
      @portfolios = Portfolio.published
    end  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
      redirect_to portfolios_path
    end

    render nothing: true
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
      if @portfolio.save
        redirect_to portfolio_path(@portfolio)
      else
        render :new
      end
  end

  def edit
  end
  
  def update
      if @portfolio.update(portfolio_params)
        @portfolio.save
        redirect_to @portfolio, notice: 'Your portfolio was edited successfully'
      else
        render :edit, notice: "Error updating your portfolio"
      end
  end

  def show
    @portfolio = Portfolio.friendly.find(params[:id])
    @gallery_items = GalleryItem.where(portfolio_id: @portfolio.id)
  end
  
  def destroy
    if @portfolio.destroy
          redirect_to portfolios_path, notice: 'Your portfolio was destroyed successfully'
      else
        render :show, notice: 'Your portfolio could not be destroyed'
      end
  end



  def toggle_status
    if @portfolio.draft?
      @portfolio.published!
    elsif @portfolio.published?
      @portfolio.draft!
    end      
    redirect_to portfolio_path, notice:  "#{@portfolio.title} status has been updated."
  end


  private

    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :description, 
                                        :main_image, 
                                        :thumbnail_image, 
                                        :url, 
                                        gallery_items_attributes: 
                                          [ :id, 
                                            :title, 
                                            :image, 
                                            :description, 
                                            :_destroy],

                                        technologies_attributes: 
                                          [:id, 
                                            :title,
                                            :_destroy])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

 def image_generator(height:, width:)
	"http://via.placeholder.com/#{height}x#{width}"
  end

	  def portfolio_img img, type


    if type == "thumb"
      if img.model.thumbnail_image?
        img
      else
        image_generator(height: '208', width: '124')
      end
    elsif type == 'main'
      if img.model.main_image?
        img
      else
        image_generator(height: '600', width: '400')
      end
    end

  end


  def gallery_img img, type
    if img.model.image?
      img
    elsif type == 'thumb'
      image_generator(height: '208', width: '124')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end

end

app/views/portfolios/_form.html.erb
<div class="row justify-content-md-center">
<div class="col-md-8 about-us" >

<%= form_for @portfolio do |f| %>
<div class="row">
  <div class="col-md-4">
    <div>
    <%= f.text_field :title, placeholder: 'Title', class: "form-control" %><br />
    </div>

    <div>
    <%= f.text_field :subtitle, placeholder: 'Subtitle', class: "form-control" %><br />
    </div>

    <div>
    <%= f.text_field :url, placeholder: 'URL', class: "form-control" %><br />
    </div>
  </div>

  <div class="col-md-8">
  <%= f.text_area :description, placeholder: 'Description', class: "form-control", rows: 6 %><br />
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="form-group col-md-6">
  	<%= f.label :main_image, "Main Image" %><br />
  	<%= f.file_field :main_image %>
  </div>

  <div class="form-group col-md-6">
  	<%= f.label :thumbnail_image, "Thumbnail Image" %><br />
  	<%= f.file_field :thumbnail_image %>
  </div>
</div>


  <%= f.fields_for :technologies do |technology|  %>
    <%= render 'technology_fields', f: technology %>
  <% end %>


<div> <%= link_to_add_association 'Add Technology', f, :technologies %> </div>
<div> <%= link_to_add_association 'Add GalleryItem', f, :gallery_items %> </div>

<p>NOTICE: THUMBNAIL IMAGE SIZES ARE PLACED IN A 208x124 AREA, IF IMAGES UPLOADED ARE A DIFFERENT ASPECT RATIO THEY WILL BE DISTORED</p>

<%= f.submit 'Submit', class: "btn btn-outline-dark" %>

<% end %>
</div>
</div>

app/views/portfolios/_gallery_item_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.label :description %>
    <%= f.text_field :description %>

  <%= link_to_remove_association 'Remove Gallery Item', f %>
</div>

app/views/portfolios/_modalImage.html.erb
<script>
  $( document ).ready(function() {
    var modal = document.getElementById('myModal');


var img = document.getElementById('myImg');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
}


var span = document.getElementsByClassName("close")[0];


span.onclick = function() { 
  modal.style.display = "none";
}
;
});
</script>

app/views/portfolios/_portfolio_item.html.erb
	<a href="<%= portfolio_path(portfolio_item) %>">
<div  class="col-md-4">
  <div  class="card about-us portfolio-margin" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumbnail_image, 'thumb'), width: '100%', :class => "thumb-image-portfolio" %>
    <p class="card-text">
      <span><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></span> <%= portfolio_item.subtitle.truncate(20) %>
    </p>
  </div>
</div>
</a>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :title %>
    <%= f.text_field :title %>
	<%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<%= render 'form' %>

app/views/portfolios/index.html.erb
  	<div class='page-title'>
  		<h1>Portfolios of Previous Work</h1>

      <% if logged_in?(:admin) %> 
  		  <%= link_to "New Portfolio", new_portfolio_path, class: "btn btn-outline-dark" %>
      <% end %>

  	</div>
<div class="album text-muted">
  <div class="container">

    <div class="row portfolio-item sortable">
      <%= render partial: 'portfolio_item', collection: @portfolios %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<%= render 'form' %>

app/views/portfolios/show.html.erb
<h1 class="page-title"> <%= @portfolio.title.titleize %></h1>
<h3> <%= @portfolio.subtitle.titleize %></h3>

<div class="row justify-content-md-center">
	<% if logged_in?(:admin) %>
	<div class="about-us col-md-3 margin-20">
		<h4>ADMIN OPTIONS</h4>
		<%= link_to "Edit", edit_portfolio_path(@portfolio), class: "about-us pageinate" %>
		<%= link_to "Delete", @portfolio, method: :delete, data:  {confirm: "Are you sure you want to delete?"},class: "about-us pageinate" %>
		<%= link_to "#{@portfolio.status}", toggle_status_portfolio_path(@portfolio), class: "about-us pageinate #{@portfolio.status}" %>
	</div>
	<% end %>

</div>
<div class="row justify-content-md-center">
	<div class="col-md-5 margin-20">
		<div class="row">
			<div class="col-md-12 about-us ">

				<!-- Trigger the Modal -->
				<%= image_tag portfolio_img(@portfolio.main_image, 'main'), width: '100%', :id => "myImg" %>
				(click to enlarge)
			</div>
			<% if (@portfolio.url && @portfolio.url != "" ) || @portfolio.technologies.length > 0 %>
			<div class="col-md-12 about-us page-title ">
				<% if (@portfolio.url && @portfolio.url != "" ) %>
				<h4>Visit This Page! </h4>
				<h5><%= link_to "#{@portfolio.url}", "http://#{@portfolio.url}", :target => "blank" %> <h5>

          <% end %>
          <% if @portfolio.technologies.length > 0 %>
          <h4>Technologies Used In Application </h4>
          <% @portfolio.technologies.each do |tech| %>
          <div class="alight-right">
            <%= markdown "* #{tech.title}" %>
          </div>
          <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-6 about-us margin-20">
      <div class="alight-right"><%= markdown @portfolio.description %></div>
    </div>
  </div>
</div>

<!-- This is the javascript call -->
<%= render "modalImage" %>


<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->


  <!-- Modal Caption (Image Text) -->

  <div class="carousel slide row justify-content-md-center" id="carousel-10262">
    <div class="col-md-3">

      <ul class="no-dot">
        <li data-slide-to="0" data-target="#carousel-10262" class="active">
          <%= image_tag(@portfolio.main_image, class: "", size: "100x70") %>
        </li>

        <!-- TODO PUT THIS IN A LOOP -->
        <% @portfolio.gallery_items.length.times do |i| %>
        <li data-slide-to="<%= i + 1 %>" data-target="#carousel-10262">
          <div class="margin-20">
            <%= image_tag(@portfolio.gallery_items[i].image, class: "", size: "100x70") %>
          </div>

        </li>
        <% end %>

      </ul>
    </div>

    <div class="col-md-1">
      <a class="carousel-control-prev" href="#carousel-10262" data-slide="prev">
        <span class="carousel-control-prev-icon"></span> 
        <span class="sr-only">Previous</span>
      </a> 
    </div>
    <div class="carousel-inner col-md-6">
      <!-- FIRST IMAGE -->
      <div class="carousel-item active">
        <%= image_tag(@portfolio.main_image, class: "modal-content", id: "img01", size: "700x467") %>
        <div class="carousel-caption">
        </div>
      </div>
      <!-- OTHER IMAGES -->
      <% @portfolio.gallery_items.each do |gallery_item| %>
      <div class="carousel-item">

        <%= image_tag(gallery_item.image, size: "700x467") %>
        <div class="page-title">
          <h3>
            <%= gallery_item.title %>
          </h3>
          <p>
            <%= gallery_item.description %>
          </p>
        </div>
      </div>
      <% end %>
    </div>   
    <div class="col-md-1">

      <a class="carousel-control-next" href="#carousel-10262" data-slide="next">
        <span class="carousel-control-next-icon"></span> 
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>