config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  
  resources :portfolios do
    put :sort, on: :collection
    member do 
      get :toggle_status
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
  
  get 'support', to: 'support#new', as: 'new_support'
  post 'support', to: 'support#create', as: 'create_support'

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

end

app/models/support.rb
class Support
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/controllers/support_controller.rb
class SupportController < ApplicationController

  def new
    @support = Support.new
  end

  def create
    @support = Support.new support_params

    if @support.valid?
      SupportMailer.contact(@support).deliver_now
      redirect_to new_support_url, notice: "Message received"
    else
      render :new
    end
  end

  private

  def support_params
    support_params = params.require(:support).permit(:name, :email, :body)
  end
end

app/views/support/new.html.erb
<%= form_for @support, url: create_support_url do |f| %>
<%= notice %>
<%= @support.errors.full_messages.join(', ') %>
<div class="row justify-content-md-center">
  <div class="about-us col-md-8">
    <div> Phone: (801) 558 4126 </div>
    <div> Mailing: 11448 S 1380 E Sandy, UT 84092</div>
    <div>(Please allow up to 24 hours for a reply)</div>
    <div>
      <div class="row justify-content-md-center page-title">
        <div class="col-md-6">
          <p><%= f.text_field :name, placeholder: 'Name', class: "form-control" %></p>
        </div>
        <div class="col-md-6">
          <p><%= f.email_field :email, placeholder: 'Email', class: "form-control" %></p>
        </div>
      </div>
      <div class="row justify-content-md-center">
        <div class="col-md-12">
          <p><%= f.text_area :body, placeholder: 'Body', class: "form-control", rows: "6" %></p>
        </div>
      </div>
      <%= f.submit 'Send', class: 'btn btn-outline-dark' %>
      <% end %>
    </div>
    <hr>
    <div><%= link_to "Have a business inquiry?", new_message_path, class: 'btn btn-outline-dark' %></div>
  </div>
</div>